- defaults:
    link:
      force: true
      relink: true
    shell:
      stderr: true

- clean: ["~"]

- shell:
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.zshrc: zsh/zshrc
    ~/.zprofile:
      if: "[[ $SHELL == *'zsh' ]]"
      path: zsh/zprofile
    ~/.profile:
      if: "[[ $SHELL == *'bash' ]]"
      path: profile.sh
    ~/.gitconfig: git.config
    ~/.ssh/config:
      if: "[[ $$(uname -s) == Darwin ]]"
      path: ssh.config
    ~/.config/pypoetry/config.toml:
      if: "[[ $$(uname -s) == Linux ]]"
      path: poetry.toml
