# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to zsh config
ZSH_CUSTOM="$HOME/.dotfiles/zsh"

# Path to oh-my-zsh installation.
export ZSH="$ZSH_CUSTOM/oh-my-zsh"

# set the prompt theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# set the oh-my-zsh plugins to use
plugins=(
    zsh-autosuggestions
    zsh-syntax-highlighting
    history-substring-search
    extract
    bgnotify
)
(( $+commands[fzf] )) && plugins+=(zsh-interactive-cd)

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source the Powerlevel10k settings
[[ ! -f ~/$ZSH_CUSTOM/p10k.zsh ]] || source ~/$ZSH_CUSTOM/p10k.zsh

# set the syntax highlighting theme
source "$ZSH_CUSTOM/themes/dracula-syntax-highlighting/zsh-syntax-highlighting.sh"

# set the ls color theme
case "$OSTYPE" in
    darwin*)
        export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
esac
export LS_COLORS="di=1;34:ln=1;36:so=1;31:pi=1;33:ex=1;32:bd=1;34;46:cd=1;34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43"

# setup colors for tab completion
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='code'
fi

# set custom aliases
alias python="python3"
alias python-config="python3-config"
alias pip="pip3"

# command to print a 256-color lookup table
# these are all 8-bit colors
color_table(){
  for i in {0..15}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}
  done
  echo " "
  for i in {16..255}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}
  done
  echo " "
}

# setup conda/mamba
for CONDA_PREFIX in \
    "/opt/homebrew/Caskroom/mambaforge/base" \
    "/astro/store/epyc/ssd/users/jfc20/mambaforge"
do
    if [ -f "$CONDA_PREFIX/etc/profile.d/conda.sh" ]; then
        . "$CONDA_PREFIX/etc/profile.d/conda.sh"
        . "$CONDA_PREFIX/etc/profile.d/mamba.sh"
        break
    fi
done

# export zenodo token
if [ -f "$HOME/.zenodo_token" ]; then
    source "$HOME/.zenodo_token"
fi

# export zotero token
if [ -f "$HOME/.zotero_token" ]; then
    source "$HOME/.zotero_token"
fi

# export overleaf credentials
if [ -f "$HOME/.overleaf_credentials" ]; then
    source "$HOME/.overleaf_credentials"
fi

# export github credentials
if [ -f "$HOME/.github_token" ]; then
    source "$HOME/.github_token"
fi

# Background check: warn if dotfiles are behind remote (skipped on HPC jobs)
if [[ -z "$SLURM_JOB_ID" ]]; then
    (
        sleep 1
        nc -z -w2 github.com 443 2>/dev/null || exit 0
        git -C "$HOME/.dotfiles" fetch origin -q 2>/dev/null || exit 0
        behind=$(git -C "$HOME/.dotfiles" rev-list HEAD..@{u} --count 2>/dev/null)
        (( behind > 0 )) && print "\n\033[33mwarning: dotfiles are $behind commit(s) behind remote\033[0m"
    ) &!
fi

# Epyc and Baldur
# ---------------
# name my main working directories on epyc
[ -d "/astro/store/epyc/users/jfc20" ] && hash -d work=/astro/store/epyc/users/jfc20
[ -d "/astro/store/epyc/ssd/users/jfc20" ] && hash -d soft=/astro/store/epyc/ssd/users/jfc20

# NERSC Perlmutter
# ----------------
# setup lbg-env
lbg_setup_file=/global/common/software/m1727/groups/WLSS/LBG/lbg-env/scripts/setup_lbg_env.sh
if [ -f $lbg_setup_file ]; then
    source $lbg_setup_file
fi

# name the PZ WG directory
pz_dir=/global/cfs/cdirs/lsst/groups/PZ
[ -d "$pz_dir" ] && alias pz='cd $pz_dir' && hash -d pz=$pz_dir

# VSCode integrated terminals don't inherit shell functions defined during setup
# of the login shell. The following re-sources the Lmod init to fix this,
# using the already-set $MODULESHOME. (this is for Perlmutter)
if [[ -n "$MODULESHOME" && "${+functions[module]}" -eq 0 ]]; then
    source "$MODULESHOME/init/zsh"
fi
