# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to zsh config
ZSH_CUSTOM="$HOME/.dotfiles/zsh"

# Path to oh-my-zsh installation.
export ZSH="$ZSH_CUSTOM/oh-my-zsh"

# set the prompt theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# set the oh-my-zsh plugins to use
plugins=(
    poetry
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source the Powerlevel10k settings
[[ ! -f ~/$ZSH_CUSTOM/p10k.zsh ]] || source ~/$ZSH_CUSTOM/p10k.zsh

# set the syntax highlighting theme
source "$ZSH_CUSTOM/themes/dracula-syntax-highlighting/zsh-syntax-highlighting.sh"

# set the ls color theme
case "$OSTYPE" in
    darwin*)
        export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
esac
export LS_COLORS="di=1;34:ln=1;36:so=1;31:pi=1;33:ex=1;32:bd=1;34;46:cd=1;34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43"

# setup colors for tab completion
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# set custom aliases
alias python="python3"
alias python-config="python3-config"
alias pip="pip3"

# command to print a 256-color lookup table
# these are all 8-bit colors
color_table(){
  for i in {0..15}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}
  done
  echo " "
  for i in {16..255}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}
  done
  echo " "
}

# setup conda
if [ -f "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/conda.sh" ]; then
    . "/opt/homebrew/Caskroom/mambaforge/base/etc/profile.d/conda.sh"
elif [ -f "/epyc/users/jfc20/local/mambaforge/etc/profile.d/conda.sh" ]; then
    . "/epyc/users/jfc20/local/mambaforge/etc/profile.d/conda.sh"
fi

# export zenodo token
if [ -f "$HOME/.zenodo_token" ]; then
    source "$HOME/.zenodo_token"
fi
